name: segmentation

channels:
    - defaults
    - conda-forge
    - awolny

dependencies:
    # core
    - python=3.7

    # linter
    - flake8
    
    # formatter
    - black

    # libraries from conda has mkl support
    - numpy
    - scipy

    # model
    - pytorch-3dunet

