#!/usr/bin/env bash

terminate_ssh() {
    echo "SIGTERM, terminating the forward tunnel"
    ssh -S tunnel.socket -O exit warp
    rm -f tunnel.socket
}

trap terminate_ssh SIGTERM SIGKILL

if [ "$1" == "" ]; then
    echo "logdir not specified"
    exit 1
fi
CONFIG_PATH=$1

NODES="g01"

conda_base=$(conda info --base)

# submit training task
# NOTE 
#   - force TTY allocation for interactive mode
#   - `script` to own the shell
ssh warp -t <<EOF
    script /dev/null
    TERM=vt100 screen -t train bash
    qsub \
        -q gpu \
        -l nodes=${NODES}:ppn=1 \
        -v conda_base=${conda_base},config_path=${CONFIG_PATH} \
        train.sh
EOF

# launch tensorboard in remote
LOG_DIR="$(dirname "${CONFIG_PATH}")/checkpoint"
ssh warp -t <<EOF
    script /dev/null
    TERM=vt100 screen -t tensorboard bash
    tensorboard --logdir ${LOG_DIR}
EOF

# port forwarding
ssh -v -N \
    -M -S tunnel.socket \
    -L 6006:localhost:6006 \
    warp
